# Conclusion

## Exploration

Through our analysis on all valid New York City crime records from 2013 to 2022, we explored several distinctive characteristics that respond to our initial research questions. We have found that Robbery and Assault crime types have the highest frequency while Murder and Fraud crime types have the lowest frequency in total. 

From Geographic analysis, we conclude that crimes are more likely to occur in Brooklyn and Manhattan boroughs than Queens and Bronx. Specifically, Downtown and Harlem in Manhattan, Bedford-Stuyvesant and Browns Ville in Brooklyn and South Bronx in Bronx are districts with the most crimes. 

In addition, according to our analysis on victim attributes with crime types they encountered, we found that males in Asian or White race group with age between 25 and 44 have the highest probability to become victims of Robbery crimes; females in White Hispanic or Other race group with age under 18 are more likely to become victims of Sexual crimes; people in Black race group, despite of their genders, have the highest frequency to suffer from Assault crimes.

From our Time Series analysis, we discovered that crimes are more likely to occur from June to August while are less likely to occur from November to January within a year. Moreover, the occurrence of crime reaches its lowest frequency in the morning then gradually goes up and reaches its peak between 3 and 5 p.m. within a day. 

## Limitation

There are two major limitations in our research. One limitation is that we remove many observations with Unknown values in Victim Race & Victim Age Group in geographic analysis. We assumed these observations are uniformly distributed in each borough of NYC. However, according to two tables that summarize the geographic distribution of observations with missing values, Manhattan borough has significantly more observations with Unknown values in variable VIC_RACE and VIC_AGE_GROUP. It doesn’t match our assumption and would cause our geographic analysis reduce the density of each type of victim race and victim age group in Manhattan on density maps.

Another crucial limitation is we mainly used one data source in our analysis, which is the “NYPD Complaint Data Current(Year To Date)” dataset from NYC Open Data website. Although NYPD has sufficient authority to ensure accuracy, authenticity as well as completeness of all crime records in this dataset, it might still have some minor errors or mistakes during the data collecting and generating process. If we can compare our data source with some other related NYC crime record datasets or research, we can not only avoid errors in NYPD Complaint Data based on comparisons, but also enhance the credibility as well as precision of our results.

## Future Directions And Lessons Learned

If we have opportunities to conduct further research on our project, we have three directions in general. Firstly, we want to analyze patterns of crime type frequency in a longer time period more than 10 years. Such analysis could help us figure out crime type frequency change along the time. The second direction is investigating suspect characteristics corresponding to crime types and geographic locations. This analysis will provide general patterns of suspects and assist people in preventing crime occurrence. Last but not the least, we want to find more NYC crime related papers and research to check if our results are accurate in matching the common findings.

We also learned numerous skills and analysis methods by making this project. We have practiced how to make a density map graph using data with exact location coordinates. Additionally, we learned how to transform original dataset into a more selective one that satisfy our requirements for research topics. These lessons learned can be used to improve our performance in future projects and future stages of current project.