<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Data | NYC crimes</title>
  <meta name="description" content="Chapter 3 Data | NYC crimes" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Data | NYC crimes" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Data | NYC crimes" />
  
  
  

<meta name="author" content="Shumin, Xinhao, and Yuta" />


<meta name="date" content="2023-01-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="proposal.html"/>
<link rel="next" href="results.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="libs/plotly-binding-4.10.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>




<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">NYC Crime</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="proposal.html"><a href="proposal.html"><i class="fa fa-check"></i><b>2</b> Proposal</a>
<ul>
<li class="chapter" data-level="2.1" data-path="proposal.html"><a href="proposal.html#research-topic"><i class="fa fa-check"></i><b>2.1</b> Research topic</a></li>
<li class="chapter" data-level="2.2" data-path="proposal.html"><a href="proposal.html#data-availability"><i class="fa fa-check"></i><b>2.2</b> Data availability</a></li>
<li class="chapter" data-level="2.3" data-path="proposal.html"><a href="proposal.html#data-format"><i class="fa fa-check"></i><b>2.3</b> Data format</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>3</b> Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data.html"><a href="data.html#sources"><i class="fa fa-check"></i><b>3.1</b> Sources</a></li>
<li class="chapter" data-level="3.2" data-path="data.html"><a href="data.html#cleaning-transformation"><i class="fa fa-check"></i><b>3.2</b> Cleaning / transformation</a></li>
<li class="chapter" data-level="3.3" data-path="data.html"><a href="data.html#missing-value-analysis"><i class="fa fa-check"></i><b>3.3</b> Missing value analysis</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="results.html"><a href="results.html"><i class="fa fa-check"></i><b>4</b> Results</a>
<ul>
<li class="chapter" data-level="4.1" data-path="results.html"><a href="results.html#time-series-analysis"><i class="fa fa-check"></i><b>4.1</b> Time series analysis</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="results.html"><a href="results.html#frequency-analysis"><i class="fa fa-check"></i><b>4.1.1</b> Frequency Analysis</a></li>
<li class="chapter" data-level="4.1.2" data-path="results.html"><a href="results.html#law-category-analysis"><i class="fa fa-check"></i><b>4.1.2</b> Law Category Analysis</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="results.html"><a href="results.html#analysis-for-relation-between-victim-and-crime-type"><i class="fa fa-check"></i><b>4.2</b> Analysis for Relation between Victim and Crime Type</a></li>
<li class="chapter" data-level="4.3" data-path="results.html"><a href="results.html#geographic-analysis"><i class="fa fa-check"></i><b>4.3</b> Geographic Analysis</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="results.html"><a href="results.html#borough-analysis"><i class="fa fa-check"></i><b>4.3.1</b> Borough Analysis</a></li>
<li class="chapter" data-level="4.3.2" data-path="results.html"><a href="results.html#analysis-for-whole-area-of-nyc"><i class="fa fa-check"></i><b>4.3.2</b> Analysis for Whole Area of NYC</a></li>
<li class="chapter" data-level="4.3.3" data-path="results.html"><a href="results.html#analysis-for-the-area-near-columbia-university"><i class="fa fa-check"></i><b>4.3.3</b> Analysis for the area near Columbia University</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="interactive-component.html"><a href="interactive-component.html"><i class="fa fa-check"></i><b>5</b> Interactive component</a></li>
<li class="chapter" data-level="6" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="6.1" data-path="conclusion.html"><a href="conclusion.html#exploration"><i class="fa fa-check"></i><b>6.1</b> Exploration</a></li>
<li class="chapter" data-level="6.2" data-path="conclusion.html"><a href="conclusion.html#limitation"><i class="fa fa-check"></i><b>6.2</b> Limitation</a></li>
<li class="chapter" data-level="6.3" data-path="conclusion.html"><a href="conclusion.html#future-directions-and-lessons-learned"><i class="fa fa-check"></i><b>6.3</b> Future Directions And Lessons Learned</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">NYC crimes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Data<a href="data.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="sources" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Sources<a href="data.html#sources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As discussed in 2.2, data is downloaded from <a href="https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243" class="uri">https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Current-Year-To-Date-/5uac-w243</a>.</p>
</div>
<div id="cleaning-transformation" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Cleaning / transformation<a href="data.html#cleaning-transformation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The format of dataset is described in section 2.3. In this section, we want to do some cleaning and transformation to the raw dataset to make it tidy.</p>
<ol style="list-style-type: decimal">
<li><p>We transform the type of columns to match it’s description. For example, we transform the type of <strong>ADDR_PCT_CD</strong> to numeric, as it describes the precinct in which the incident occurred. Also, we transform the type of <strong>CMPLNT_FR_DT</strong> into date, as it describes exact date of occurrence for the reported event.</p></li>
<li><p>We drop the columns carrying the same information. For example, <strong>Lat_Lon.Latitude</strong> is exactly the same as <strong>Lat_Lon.Latitude</strong>, and <strong>Lat_Lon.Longitude</strong> is identical to <strong>Longitude</strong>. Moreover, <strong>New Georeferenced Column</strong> is just the combination of <strong>Latitude</strong> and <strong>Longitude</strong>. Therefore, we drop
<strong>Lat_Lon</strong> and <strong>New Georeferenced Column</strong> in our dataset.</p></li>
<li><p>we drop the unreasonable rows. For example, there are crimes starting at year 1011, which we believe is a mistake. In addition, in the suspect’s and victim’s ages, there are negative values. So we drop the rows with such mistakes.</p></li>
<li><p>We factorize some variables. For example, <strong>ADDR_PCT_CD</strong> describes the precinct in which the incident occurred, so instead of integer, it should be factor. Moreover, some factors are ordinal, like <strong>LAW_CAT_CD</strong>, it describes the level of offense: felony, misdemeanor, violation, and <strong>SUSP_AGE_GROUP</strong>, which is the suspect’s age group.</p></li>
</ol>
<p>After cleaning and transforming, the description and the class of each column is shown in the table below:</p>
<table>
<colgroup>
<col width="11%" />
<col width="83%" />
<col width="5%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Colname</th>
<th align="left">Description</th>
<th align="left">Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ADDR_PCT_CD</td>
<td align="left">The precinct in which the incident occurred</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">BORO_NM</td>
<td align="left">The name of the borough in which the incident occurred</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">CMPLNT_FR_DT</td>
<td align="left">Exact date of occurrence for the reported event (or starting date of occurrence, if CMPLNT_TO_DT exists)</td>
<td align="left">Date</td>
</tr>
<tr class="even">
<td align="left">CMPLNT_FR_TM</td>
<td align="left">Exact time of occurrence for the reported event (or starting time of occurrence, if CMPLNT_TO_TM exists)</td>
<td align="left">character</td>
</tr>
<tr class="odd">
<td align="left">CMPLNT_NUM</td>
<td align="left">Randomly generated persistent ID for each complaint</td>
<td align="left">character</td>
</tr>
<tr class="even">
<td align="left">CMPLNT_TO_DT</td>
<td align="left">Ending date of occurrence for the reported event, if exact time of occurrence is unknown</td>
<td align="left">Date</td>
</tr>
<tr class="odd">
<td align="left">CMPLNT_TO_TM</td>
<td align="left">Ending time of occurrence for the reported event, if exact time of occurrence is unknown</td>
<td align="left">character</td>
</tr>
<tr class="even">
<td align="left">CRM_ATPT_CPTD_CD</td>
<td align="left">Indicator of whether crime was successfully completed or attempted, but failed or was interrupted prematurely</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">HADEVELOPT</td>
<td align="left">Name of NYCHA housing development of occurrence, if applicable</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">HOUSING_PSA</td>
<td align="left">Development Level Code</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">JURIS_DESC</td>
<td align="left">Description of the jurisdiction code</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">JURISDICTION_CODE</td>
<td align="left">Jurisdiction responsible for incident. Either internal, like Police(0), Transit(1), and Housing(2); or external(3), like Correction, Port Authority, etc.</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">KY_CD</td>
<td align="left">Three digit offense classification code</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">LAW_CAT_CD</td>
<td align="left">Level of offense: felony, misdemeanor, violation</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">LOC_OF_OCCUR_DESC</td>
<td align="left">Specific location of occurrence in or around the premises; inside, opposite of, front of, rear of</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">OFNS_DESC</td>
<td align="left">Description of offense corresponding with key code</td>
<td align="left">character</td>
</tr>
<tr class="odd">
<td align="left">PARKS_NM</td>
<td align="left">Name of NYC park, playground or greenspace of occurrence, if applicable (state parks are not included)</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">PATROL_BORO</td>
<td align="left">The name of the patrol borough in which the incident occurred</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">PD_CD</td>
<td align="left">Three digit internal classification code (more granular than Key Code)</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">PD_DESC</td>
<td align="left">Description of internal classification corresponding with PD code (more granular than Offense Description)</td>
<td align="left">character</td>
</tr>
<tr class="odd">
<td align="left">PREM_TYP_DESC</td>
<td align="left">Specific description of premises; grocery store, residence, street, etc.</td>
<td align="left">character</td>
</tr>
<tr class="even">
<td align="left">RPT_DT</td>
<td align="left">Date event was reported to police</td>
<td align="left">Date</td>
</tr>
<tr class="odd">
<td align="left">STATION_NAME</td>
<td align="left">Transit station name</td>
<td align="left">character</td>
</tr>
<tr class="even">
<td align="left">SUSP_AGE_GROUP</td>
<td align="left">Suspect’s Age Group</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">SUSP_RACE</td>
<td align="left">Suspect’s Race Description</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">SUSP_SEX</td>
<td align="left">Suspect’s Sex Description</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">TRANSIT_DISTRICT</td>
<td align="left">Transit district in which the offense occurred.</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">VIC_AGE_GROUP</td>
<td align="left">Victim’s Age Group</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">VIC_RACE</td>
<td align="left">Victim’s Race Description</td>
<td align="left">factor</td>
</tr>
<tr class="even">
<td align="left">VIC_SEX</td>
<td align="left">Victim’s Sex Description</td>
<td align="left">factor</td>
</tr>
<tr class="odd">
<td align="left">X_COORD_CD</td>
<td align="left">X-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)</td>
<td align="left">numeric</td>
</tr>
<tr class="even">
<td align="left">Y_COORD_CD</td>
<td align="left">Y-coordinate for New York State Plane Coordinate System, Long Island Zone, NAD 83, units feet (FIPS 3104)</td>
<td align="left">numeric</td>
</tr>
<tr class="odd">
<td align="left">Geocoded_Column.type</td>
<td align="left">Type of the geographical location</td>
<td align="left">factor</td>
</tr>
</tbody>
</table>
</div>
<div id="missing-value-analysis" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Missing value analysis<a href="data.html#missing-value-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the dataset, there are missing values and values marked as Unknown.</p>
<table>
<thead>
<tr class="header">
<th align="left">variables</th>
<th align="right">na_nums</th>
<th align="right">unknown_nums</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">cmplnt_num</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">addr_pct_cd</td>
<td align="right">20</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">boro_nm</td>
<td align="right">657</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">cmplnt_fr_dt</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cmplnt_fr_tm</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">cmplnt_to_dt</td>
<td align="right">29380</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">cmplnt_to_tm</td>
<td align="right">29262</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">crm_atpt_cptd_cd</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hadevelopt</td>
<td align="right">395630</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">jurisdiction_code</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">juris_desc</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">ky_cd</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">law_cat_cd</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">loc_of_occur_desc</td>
<td align="right">66072</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">ofns_desc</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">parks_nm</td>
<td align="right">394169</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">patrol_boro</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">pd_cd</td>
<td align="right">437</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">pd_desc</td>
<td align="right">437</td>
<td align="right">1221</td>
</tr>
<tr class="even">
<td align="left">prem_typ_desc</td>
<td align="right">474</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">rpt_dt</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">station_name</td>
<td align="right">388551</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">susp_age_group</td>
<td align="right">73511</td>
<td align="right">152659</td>
</tr>
<tr class="even">
<td align="left">susp_race</td>
<td align="right">73511</td>
<td align="right">99078</td>
</tr>
<tr class="odd">
<td align="left">susp_sex</td>
<td align="right">73511</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">vic_age_group</td>
<td align="right">0</td>
<td align="right">111822</td>
</tr>
<tr class="odd">
<td align="left">vic_race</td>
<td align="right">104</td>
<td align="right">119927</td>
</tr>
<tr class="even">
<td align="left">vic_sex</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">x_coord_cd</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">y_coord_cd</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">latitude</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">longitude</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">geocoded_column.type</td>
<td align="right">9</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">housing_psa</td>
<td align="right">371401</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">transit_district</td>
<td align="right">388551</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><img src="finalproj_files/figure-html/redav-1.png" width="1440" /></p>
<div id="htmlwidget-9f25bc52186a67c54972" style="width:672px;height:960px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-9f25bc52186a67c54972">{"x":{"visdat":{"1009f3f37a1f8":["function () ","plotlyVisDat"]},"cur_data":"1009f3f37a1f8","attrs":{"1009f3f37a1f8":{"x":{},"y":{},"orientation":"h","marker":{"color":"cadeblue2"},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":70,"l":100,"t":70,"r":20},"title":"Bar chart of number of NA values in each variable from dataset","legend":{"x":0,"y":0,"font":{"size":10}},"xaxis":{"domain":[0,1],"automargin":true,"title":"na_nums"},"yaxis":{"domain":[0,1],"automargin":true,"title":"variables","type":"category","categoryorder":"array","categoryarray":["addr_pct_cd","boro_nm","cmplnt_fr_dt","cmplnt_fr_tm","cmplnt_num","cmplnt_to_dt","cmplnt_to_tm","crm_atpt_cptd_cd","geocoded_column.type","hadevelopt","housing_psa","juris_desc","jurisdiction_code","ky_cd","latitude","law_cat_cd","loc_of_occur_desc","longitude","ofns_desc","parks_nm","patrol_boro","pd_cd","pd_desc","prem_typ_desc","rpt_dt","station_name","susp_age_group","susp_race","susp_sex","transit_district","vic_age_group","vic_race","vic_sex","x_coord_cd","y_coord_cd"]},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[0,20,657,0,0,29380,29262,0,395630,0,0,0,0,66072,5,394169,2,437,437,474,0,388551,73511,73511,73511,0,104,0,9,9,9,9,9,371401,388551],"y":["cmplnt_num","addr_pct_cd","boro_nm","cmplnt_fr_dt","cmplnt_fr_tm","cmplnt_to_dt","cmplnt_to_tm","crm_atpt_cptd_cd","hadevelopt","jurisdiction_code","juris_desc","ky_cd","law_cat_cd","loc_of_occur_desc","ofns_desc","parks_nm","patrol_boro","pd_cd","pd_desc","prem_typ_desc","rpt_dt","station_name","susp_age_group","susp_race","susp_sex","vic_age_group","vic_race","vic_sex","x_coord_cd","y_coord_cd","latitude","longitude","geocoded_column.type","housing_psa","transit_district"],"orientation":"h","marker":{"color":"cadeblue2","line":{"color":"rgba(31,119,180,1)"}},"type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<div id="htmlwidget-d947df05786f93294a55" style="width:672px;height:960px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-d947df05786f93294a55">{"x":{"visdat":{"1009fbb26cd6":["function () ","plotlyVisDat"]},"cur_data":"1009fbb26cd6","attrs":{"1009fbb26cd6":{"x":{},"y":{},"orientation":"h","marker":{"color":"cadeblue2"},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"bar"}},"layout":{"margin":{"b":70,"l":100,"t":70,"r":20},"title":"Bar chart of number of Unknown values in each variable from dataset","legend":{"x":0,"y":0,"font":{"size":10}},"xaxis":{"domain":[0,1],"automargin":true,"title":"unknown_nums"},"yaxis":{"domain":[0,1],"automargin":true,"title":"variables","type":"category","categoryorder":"array","categoryarray":["addr_pct_cd","boro_nm","cmplnt_fr_dt","cmplnt_fr_tm","cmplnt_num","cmplnt_to_dt","cmplnt_to_tm","crm_atpt_cptd_cd","geocoded_column.type","hadevelopt","housing_psa","juris_desc","jurisdiction_code","ky_cd","latitude","law_cat_cd","loc_of_occur_desc","longitude","ofns_desc","parks_nm","patrol_boro","pd_cd","pd_desc","prem_typ_desc","rpt_dt","station_name","susp_age_group","susp_race","susp_sex","transit_district","vic_age_group","vic_race","vic_sex","x_coord_cd","y_coord_cd"]},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1221,0,0,0,152659,99078,0,111822,119927,0,0,0,0,0,0,0,0],"y":["cmplnt_num","addr_pct_cd","boro_nm","cmplnt_fr_dt","cmplnt_fr_tm","cmplnt_to_dt","cmplnt_to_tm","crm_atpt_cptd_cd","hadevelopt","jurisdiction_code","juris_desc","ky_cd","law_cat_cd","loc_of_occur_desc","ofns_desc","parks_nm","patrol_boro","pd_cd","pd_desc","prem_typ_desc","rpt_dt","station_name","susp_age_group","susp_race","susp_sex","vic_age_group","vic_race","vic_sex","x_coord_cd","y_coord_cd","latitude","longitude","geocoded_column.type","housing_psa","transit_district"],"orientation":"h","marker":{"color":"cadeblue2","line":{"color":"rgba(31,119,180,1)"}},"type":"bar","error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<p>Based on two horizontal bar charts above that show the total number of NA values as well as Unknown values in each variable from dataset, we can see several apparent features in missing values:</p>
<ol style="list-style-type: decimal">
<li><p>In bar chart of number of NA values, variable <strong>TRANSIT_DISTRICT</strong> and <strong>STATION_NAME</strong> are positively associated because they represent transit district in which the offense occurred and transit police station name respectively. Since each of these two variables has more than 300k NA values, which is more than 92% of total observations in dataset, and we only focus on where did a crime occur, we can drop these two variables in our result analysis part.Similarly, variable <strong>PARKS_NM, HOUSING_PSA, HADEVELOP</strong> have a positive correlation. This means if an observation has NA value in one of these three variables, then there is high probability that such observation will have NA values in other two variables. Since each of these three variables has more than 300k NA values and they are not related to our research questions, we will remove these variables in result analysis part.</p></li>
<li><p>In bar chart of number of NA values, variable <strong>SUSP_SEX, SUSP_RACE, SUSP_AGE_GROUP</strong> have same number of NA values of 73511. Moreover, if an observation has NA value in one of these three variables, then this observation record will have NA values in other two variables. Since we only focus on victims attributes in our research questions, we will remove these three variables in result analysis. Similarly, variable <strong>CMPLNT_TO_TM, CMPLNT_TO_DT</strong> have same number of NA values of 29262. Since we are only focus on occurred date of crimes, we will not include these 2 variables in our result analysis.</p></li>
<li><p>In bar chart of number of NA values, there are <strong>ADDR_PCT_CD, BORO_NM, OFNS_DESC, PATROL_BORO, PD_CD, PD_DESC, PREM_TYP_DESC, VIC_RACE, X_COORD_CD, Y_COORD_CD, Geocoded_Column.type</strong> variables having NA values that are less than 1k. We will directly delete observations with NA values in these variables in our result analysis since total number of such observations only occupy approximately 0.5% of all data.</p></li>
<li><p>In bar chart of number of Unknown values, variable <strong>VIC_RACE</strong> and <strong>VIC_AGE_GROUP</strong> have a strong positive correlation. <strong>VIC_RACE</strong> has 119.927k Unknown values while <strong>VIC_AGE_GROUP</strong> has 111.822k Unknown values, both of them occupy more than 28% of total observations. We will delete observations with Unknown values in making graphs of victim race and victim age group distribution over different areas of NYC. However, since there is a moderate portion of Unknown values in these two variables and we need to show that remaining data is not biased, we will make two tables to show distribution of observations with Unknown values in <strong>VIC_RACE</strong> and <strong>VIC_AGE_GROUP</strong> over boroughs of NYC.</p></li>
</ol>
<p><img src="finalproj_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre><code>##                
##                 FALSE  TRUE
##   BRONX         63288 19916
##   BROOKLYN      83494 26951
##   MANHATTAN     60011 40288
##   QUEENS        65060 20607
##   STATEN ISLAND 12541  4039</code></pre>
<p><img src="finalproj_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>According to these two plots, we can see that Manhattan borough has the highest percentage of Unknown values in variable <strong>VIC_RACE</strong> and <strong>VIC_AGE_GROUP</strong>. Unknown values approximately have uniform distribution in other four variables. Therefore, the removal of all observations with Unknown values in <strong>VIC_RACE</strong> and <strong>VIC_AGE_GROUP</strong> will reduce the density of each type of victim race and victim age group in Manhattan. This limitation will slightly reduce the overall accuracy of our graph.</p>
<ol start="5" style="list-style-type: decimal">
<li><p>In bar chart of number of Unknown values, variable <strong>SUSP_RACE, SUSP_AGE_GROUP</strong> have a strong positive correlation. Since each of these two variables has more than 99k Unknown values and we only focus on victims attributes in our research questions, we will remove these two variables in result analysis.</p></li>
<li><p>In bar chart of number of Unknown values, variable <strong>PD_DESC</strong> has 1221 Unknown values. Since this just occupy less than 0.5% of total data, we will directly remove observations with Unknown values in <strong>PD_DESC</strong> in our result analysis.</p></li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="proposal.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="results.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Russell-A/NYCrime/edit/main/data.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/Russell-A/NYCrime/blob/main/data.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
